name: Test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run build
      - run: npm test
