# NOTE: if you want to use this file as a template, make sure to replace 'master' in line 21
# with your repository's default branch (in case you changed it to something other than 'master')

on: [push, pull_request]
name: Toot, together!
jobs:
  preview:
    name: Preview
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run build
      - name: Preview
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tweet:
    name: Tweet
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run build
      - name: Toot
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MASTODON_URL: ${{ secrets.MASTODON_URL }}
          MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
